drop sequence if exists hibernate_sequence;
drop table if exists applications;
drop table if exists authorities;
drop table if exists degrees;
drop table if exists employer_reviews;
drop table if exists favorites;
drop table if exists job_postings cascade;
drop table if exists job_reviews;
drop table if exists jobs_applied;
drop table if exists resumes;
drop table if exists user_phones;
drop table if exists users;
